db:
  image: postgres:9.4.5
  ports:
    - '5432:5432'

backup:
  build: .
  volumes:
    - ./:/usr/src/app
  environment:
    - DBBACKUP_STORAGE='dbbackup.storage.dropbox_storage'
    - DROPBOX_ACCESS_TOKEN=YnSZmhwIVZkAAAAAAAAIl_u4ZaOMkzo30M22ItlYP4fZTlsHOm5LJzKVgxJ0OkPS
  links:
    - db:db
  ports:
    - 7000:80