db:
  image: postgres:9.4.5
  ports:
    - '5432:5432'

backup:
  build: .
  volumes:
    - ./:/usr/src/app
  environment:
    - DBBACKUP_STORAGE='dbbackup.storage.dropbox_storage'
    - DBBACKUP_TOKENS_FILEPATH=/usr/src/app/core/dropbox
    - DBBACKUP_DROPBOX_APP_KEY=5x04czxuq5phbyc
    - DBBACKUP_DROPBOX_APP_SECRET=gatqrelizrk823m
  links:
    - db:db
  ports:
    - 7000:80